### ISSUE TITLE
WIP up/down message buffer behavior breaks textbox editing expectations

### ISSUE THREAD

**Issue by gcymbalski** [lierc/lierc-basicui#15]
Namely, if you're sending a chat that spans a line and try to use arrow keys in ways you'd expect, you wind up scrolling through the message buffer. I think that's a useful feature and propose solving this by allowing scrolling through the message buffer only when holding 'control'.

**Comment by gcymbalski** [comment]
wpo pointed out that this breaks default mission control behavior in osx; probably a different approach is better.

**Comment by leedo** [comment]
updated in master to be shift+[up|down]. We'll see what  people say!

**Comment by gcymbalski** [comment]
Feels great to me :thumbsup:
