### ISSUE TITLE
'Scrolling' in Left/Channel Pane

### ISSUE THREAD

**Issue by gcymbalski** [lierc/lierc-basicui#20]
While a small thing, it'd make me happy and I'm also super bored so I'll do this later. Will solicit advice after a good look around.

(By this I mean being able to use a mousewheel or touch event to intuitively and predictably navigate around everything on the left pane in a way that feels good/makes sense)

**Comment by leedo** [comment]
Hmm, i thought this was scrollable! Maybe not on touch devices?

**Comment by gcymbalski** [comment]
Closing this ancient issue, everything's fine now!
